added default tz to clock - to overcome errors when host computer does not have tz specified
Calculating time series of subjects and records.
Error: 'unknown' not found in the timezone database.
Run `rlang::last_error()` to see where the error occurred.
Warning: unknown timezone 'unknown'
Warning: unknown timezone 'unknown'
> rlang::last_error()
<error/rlang_error>
'unknown' not found in the timezone database.
Backtrace:
  1. CohortDiagnostics::runCohortDiagnostics(...)
 14. clock::date_today("")
 16. clock:::as.Date.clock_zoned_time(zoned_time_now(zone))
 19. clock:::as_naive_time.clock_zoned_time(x)
 20. clock:::get_naive_time_cpp(x, precision, zone)
Run `rlang::last_trace()` to see the full context.